export const PROVINCIAS = [
  'Bengo',
  'Benguela',
  'Bié',
  'Cabinda',
  'Cuando Cubango',
  'Cuanza Norte',
  'Cuanza Sul',
  'Cunene',
  'Huambo',
  'Huíla',
  'Luanda',
  'Lunda Norte',
  'Lunda Sul',
  'Malanje',
  'Moxico',
  'Namibe',
  'Uíge',
  'Zaire',
] as const;

export const MODALIDADES = [
  'Andebol',
  'Atletismo',
  'Badminton',
  'Basquetebol',
  'Boxe',
  'Ciclismo',
  'Desporto Adaptado',
  'Futebol',
  'Futebol de Salão',
  'Ginástica',
  'Judô',
  'Karaté',
  'Lutas',
  'Natação',
  'Patinação',
  'Pesca Desportiva',
  'Taekwondo',
  'Ténis',
  'Ténis de Mesa',
  'Voleibol',
  'Xadrez',
] as const;
