export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/pub/register',
    LOGIN: '/auth/pub/login',
    REFRESH_TOKEN: '/auth/pub/refresh-token',
    FORGOT_PASSWORD: '/auth/pub/forgot-password',
    RESET_PASSWORD: '/auth/pub/reset-password',
    LOGOUT: '/auth/prot/logout',
    ME: '/auth/prot/me',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
  },
  FEDERACOES: {
    BASE: '/federations',
    BY_ID: (id: string) => `/federations/${id}`,
  },
  CLUBES: {
    BASE: '/clubes',
    BY_ID: (id: string) => `/clubes/${id}`,
    ASSOCIATE_ATLETA: '/clubes/associate-atleta',
  },
  ATLETAS: {
    BASE: '/atletas',
    BY_ID: (id: string) => `/atletas/${id}`,
    ME: '/atletas/me',
    ME_DASHBOARD: '/atletas/me/dashboard',
    ME_DOCUMENTOS: '/atletas/me/documentos',
    DOCUMENTOS: '/atletas/documentos',
    DOCUMENTOS_PENDENTES: '/atletas/documentos/pendentes',
    INSCRICAO: '/atletas/inscricao',
    TRANSFERIR: (id: string) => `/atletas/${id}/transferir`,
  },
  ROLES: {
    BASE: '/roles',
    ASSIGN_PERMISSION: '/roles/assign-permission',
  },
  PERMISSOES: {
    BASE: '/permissao',
  },
  PLANOS: {
    BASE: '/planos',
  },
  ASSINATURAS: {
    BASE: '/assinaturas',
    MINHAS: '/assinaturas/minhas',
    CONFIRMAR: (id: string) => `/assinaturas/${id}/confirmar`,
    CANCELAR: (id: string) => `/assinaturas/${id}/cancelar`,
    CHECKOUT_EMIS: (id: string) => `/assinaturas/${id}/checkout-emis`,
    PAYMENT_STATUS: (reference: string) => `/assinaturas/pagamento/status/${reference}`,
  },
  CAMPEONATOS: {
    BASE: '/campeonatos',
    BY_ID: (id: string) => `/campeonatos/${id}`,
    INSCREVER: (id: string) => `/campeonatos/${id}/inscrever`,
    CLASSIFICACAO: (id: string) => `/campeonatos/${id}/classificacao`,
    JOGOS: (id: string) => `/campeonatos/${id}/jogos`,
  },
  NOTIFICACOES: {
    BASE: '/notificacoes',
    ENVIAR: '/notificacoes/enviar',
    COUNT: '/notificacoes/count',
    LER_TODAS: '/notificacoes/ler',
    LER: (id: string) => `/notificacoes/${id}/ler`,
  },
  PAGAMENTOS: {
    BASE: '/pagamentos',
    BY_ID: (id: string) => `/pagamentos/${id}`,
  },
  COMPETICAO: {
    RANKING_GERAL: '/competicao/rankings/geral',
    RANKING_ATLETA: (id: string) => `/competicao/rankings/atleta/${id}`,
    RANKING_CAMPEONATO: (id: string) => `/competicao/campeonatos/${id}/ranking`,
  },
  UPLOAD: {
    SIGNATURE: '/upload/signature',
    SAVE: '/upload/save',
  },
  EVENTOS: {
    BASE: '/eventos',
    BY_ID: (id: string) => `/eventos/${id}`,
  },
  BRACKETS: {
    BASE: '/brackets',
    BY_ID: (id: string) => `/brackets/${id}`,
    GERAR: '/brackets/gerar',
    RESULTADO: (id: string) => `/brackets/${id}/resultado`,
    INVALIDAR: (id: string) => `/brackets/${id}/invalidar`,
    TROCAR: (id: string) => `/brackets/${id}/trocar`,
    PARTICIPANTE: (id: string) => `/brackets/${id}/participante`,
    REGENERAR: (id: string) => `/brackets/${id}/regenerar`,
    PROMOVER_GRUPOS: (id: string) => `/brackets/${id}/promover-grupos`,
  },
};
